config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  scope "(:locale)", locale: /en|vi/ do

    root 'songs#index'

    devise_for :users, controllers: {registrations: "users/registrations",
      sessions: "users/sessions", passwords: "users/passwords", confirmations: "users/confirmations"}

    resources :favorites, only: %i[create show destroy]
    resources :favorite_songs, only: %i[create destroy]
    resources :songs do
      resources :comments
      collection do
        get 'search'
      end
    end
    resources :authors
    resources :categories
    resources :singers
    resources :albums do
      collection do
        get 'album_song'
      end
    end
    resources :users, only: :index
    resources :likes, only: %i[create destroy]

    namespace :admins do
      resources :users
      resources :songs
      resources :authors
      resources :categories
      resources :singers
      resources :albums
    end
  end
end

app/models/category.rb
class Category < ApplicationRecord
  scope :limit_display, -> { (order created_at: :desc).limit(5) }

  validates :name, presence: true

  before_save :capitalize_name

  has_many :songs, through: :category_songs
  has_many :category_songs, dependent: :destroy

  has_many :albums, through: :album_categories
  has_many :album_categories, dependent: :destroy

  scope :sort_by_create_at, -> { order created_at: :desc }
  scope :search_by_name, ->(search) { where 'name LIKE ?', "%#{search}%" }

  def capitalize_name
    name.capitalize!
  end

  class << self
    def to_csv(options = {})
      CSV.generate options do |csv|
        csv << column_names
        all.each do |category|
          csv << category.attributes.values_at(*column_names)
        end
      end
    end

    def index_categories(params)
      if params[:search].present?
        Category.search_by_name(params[:search])
      else
        Category.includes(:songs, :albums).sort_by_create_at
      end.paginate page: params[:page], per_page: 5
    end
  end
end

app/controllers/admins/categories_controller.rb
module Admins
  class CategoriesController < ApplicationController
    layout 'application_admin'

    before_action :check_user_logged, :verify_admin
    before_action :find_category, except: %i[index new create]

    def index
      @categories = Category.index_categories params
      @category = Category.new
      respond_to do |format|
        format.html
        format.js
        format.xls { send_data Category.to_csv(col_sep: "\t") }
      end
    end

    def create
      @category = Category.new category_params
      if @category.save
        flash[:success] = 'Create Category Successfully!'
        redirect_to admins_categories_path
      else
        render :new
      end
    end

    def edit; end

    def update
      if @category.update_attributes category_params
        redirect_to admins_categories_path
        flash[:success] = 'Category Edit Successfully!'
      else
        render :edit
      end
    end

    def destroy
      if @category.destroy
        flash[:success] = 'Category Delete Successfully!'
      else
        flash[:danger] = 'Cant delete category'
      end
      redirect_to admins_categories_path
    end

    private

    def find_category
      @category = Category.find_by id: params[:id]
      return if @category
      flash[:danger] = 'Category not exist'
      redirect_to admins_categories_path
    end

    def category_params
      params.require(:category).permit :name
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.includes(:albums, albums: :songs)
  end

  def show
    @category = Category.includes(:albums, albums: :songs)
                        .find_by id: params[:id]
    @albums = Album.all
  end
end

app/views/admins/categories/_form_edit.html.erb
<%= form_for [:admins, @category], remote: true do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  <div class="row">
    <div class="col-md-8 col-md-offset-2"">
      <div class="form-group row">
        <div class="col-md-3">
          <%= f.label :name, t("views.admins.categories.text_form.name"),
            class: "col-form-label" %>
        </div>
        <div class="col-md-7">
          <%= f.text_field :name, class: "form-control" %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-md-8 col-md-offset-3">
          <%= f.submit button_to, class: "btn btn-success" %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/admins/categories/_form_new.html.erb
<%= form_for [:admins, @category], remote: true do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  <div class="row">
    <div class="col-md-8"">
      <div class="form-group row">
        <div class="col-md-5">
          <%= f.label :name, t("views.admins.categories.text_form.name"),
            class: "col-form-label" %>
        </div>
        <div class="col-md-7">
          <%= f.text_field :name, class: "form-control input-category" %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-md-8 col-md-offset-4">
          <%= f.submit button_to, class: "btn btn-success" %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/admins/categories/_list_category.html.erb
<thead>
  <tr>
    <th><%= t "views.admins.categories.text_form.name" %></th>
    <th><%= t "views.admins.songs.text_form.name" %></th>
    <th><%= t "views.admins.albums.text_form.name" %></th>
    <th class="action"><%= t "views.admins.form.action" %></th>
  </tr>
</thead>
<tbody>
  <% @categories.each do |category| %>
    <tr class="background-tr">
      <td><%= category.name %></td>
      <td>
        <ul>
          <% category.songs.each do |song| %>
            <li><%= song.name %></li>
          <% end %>
        </ul>
      </td>
      <td>
        <ul>
          <% category.albums.each do |album| %>
            <%= link_to admins_album_path(album) do %>
              <li><%= album.name %></li>
            <% end %>
          <% end %>
        </ul>
      </td>
      <td>
        <%= link_to edit_admins_category_path category do %>
          <i class="glyphicon glyphicon-pencil"></i>
        <% end %>
        <%= link_to admins_category_path(category), method: :delete,
          data: {confirm: t("views.admins.form_confirm")} do %>
          <i class="glyphicon glyphicon-trash"></i>
        <% end %>
      </td>
    </tr>
  <% end %>
</tbody>

app/views/admins/categories/_new.html.erb
<div class="form-wrap">
  <%= render "form_new", button_to: t("views.admins.categories.title.new") %>
</div>

app/views/admins/categories/edit.html.erb
<% provide :title, t("views.admins.categories.title.edit") %>
<div class="main-content">
  <div class="container">
    <div class="info-manager">
      <div class="title-manager pull-left">
        <h2><%= t "views.admins.categories.title.edit" %></h2>
      </div>
      <div class="button-manager pull-right">
        <ul>
          <li>
            <%= link_to admins_categories_path(format: "xls") do %>
              <i class="glyphicon glyphicon-export"></i>
              <%= t "button.export" %>
            <% end %>
          </li>
        </ul>
      </div>
      <div class="clearfix"></div>
    </div>
    <div class="form-wrap">
      <%= render "form_edit", button_to: t("views.admins.categories.title.save") %>
    </div>
  </div>
</div>

app/views/admins/categories/edit.js.erb
$('.form-wrap').html('<%= j render "form_edit", button_to: t("views.admins.categories.title.save") %>');

app/views/admins/categories/index.html.erb
<% provide :title, t("views.admins.categories.title.index") %>
<div class="main-content">
  <div class="container">
    <div class="info-manager">
      <div class="title-manager pull-left">
        <h2><%= t "views.admins.categories.title.index" %></h2>
      </div>
      <div class="button-manager pull-right">
        <ul>
          <li>
            <%= link_to admins_categories_path(format: "xls") do %>
              <i class="glyphicon glyphicon-export"></i>
              <%= t "button.export" %>
            <% end %>
          </li>
        </ul>
      </div>
      <div class="clearfix"></div>
    </div>
    <div class="row wrap-search">
      <div class="col-md-6 col-md-offset-6">
        <%= form_tag admins_categories_path, method: :get, remote: true do %>
          <div class="form-group pull-right">
            <%= text_field_tag :search, params[:search],
              placeholder: "Input Name Category" %>
            <%= button_tag "Search", class: "custom-btn" do %>
              <span class="glyphicon glyphicon-search"></span>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-4">
        <%= render "new" %>
      </div>
      <div class="col-md-8">
        <div class="table-responsive">
          <table class="table table-bordered table-hover">
            <%= render "list_category" %>
          </table>
          <div class="paginate">
           <%= will_paginate %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admins/categories/index.js.erb
$('.table').html('<%= j render "list_category" %>');
$('.paginate').html('<%= j will_paginate @categories %>')

app/views/admins/categories/new.js.erb
$('.form-wrap').html('<%= j render "form_new", button_to: t("views.admins.categories.title.new") %>');