config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  scope "(:locale)", locale: /en|vi/ do

    root 'songs#index'

    devise_for :users, controllers: {registrations: "users/registrations",
      sessions: "users/sessions", passwords: "users/passwords", confirmations: "users/confirmations"}

    resources :favorites, only: %i[create show destroy]
    resources :favorite_songs, only: %i[create destroy]
    resources :songs do
      resources :comments
      collection do
        get 'search'
      end
    end
    resources :authors
    resources :categories
    resources :singers
    resources :albums do
      collection do
        get 'album_song'
      end
    end
    resources :users, only: :index
    resources :likes, only: %i[create destroy]

    namespace :admins do
      resources :users
      resources :songs
      resources :authors
      resources :categories
      resources :singers
      resources :albums
    end
  end
end

app/models/song.rb
class Song < ApplicationRecord
  scope :sort_by_create_at, -> { order created_at: :desc }
  scope :top, -> { (order count_view: :desc).limit(10) }

  mount_uploader :picture, PictureUploader
  mount_uploader :file_song, AudioUploader

  validates :name, presence: true, length: { maximum: 50 }
  validates_presence_of :picture
  validates_presence_of :file_song
  validates :content, presence: true

  # Categories_Song
  has_many :categories, through: :category_songs
  has_many :category_songs, dependent: :destroy

  # Singer_Song
  has_many :singers, through: :singer_songs
  has_many :singer_songs, dependent: :destroy

  # Album_Song
  has_many :albums, through: :album_songs
  has_many :album_songs, dependent: :destroy

  # User_Song
  has_many :users, through: :user_songs
  has_many :user_songs, dependent: :destroy

  belongs_to :author
  has_many :likes
  has_many :comments

  # Favorite Song
  has_many :favorites, through: :favorite_songs
  has_many :favorite_songs, dependent: :destroy

  scope :search_song_client, ->(search) { where 'name LIKE ?', "%#{search}%" }

  scope :search_song, ->(song_name, singer_name, category_name, author_name) do
    where('songs.name LIKE ?', "%#{song_name}%")
      .joins(:singers).where('singers.name LIKE ?', "%#{singer_name}%")
      .joins(:categories).where('categories.name LIKE ?', "%#{category_name}%")
      .joins(:author).where 'authors.name LIKE ?', "%#{author_name}%"
  end

  def liked?(user)
    likes.where(user_id: user.id).present?
  end

  def commented?(user)
    comments.where(user_id: user.id).present?
  end

  class << self
    def to_csv(options = {})
      wanted_columns = %i[name file_song count_view]
      CSV.generate options do |csv|
        csv << wanted_columns.insert(-1, :count_like, :author_name,
                                     :category_name)
        all.each do |song|
          csv << song.attributes.values_at('name', 'file_song', 'count_view')
                     .insert(-1, song.likes.count, song.author.name,
                             song.categories.first.name)
        end
      end
    end
  end
end

app/controllers/admins/songs_controller.rb
module Admins
  class SongsController < ApplicationController
    layout 'application_admin'

    before_action :check_user_logged, :verify_admin
    before_action :find_song, except: %i[index new create]
    before_action :load_data, only: %i[index new edit]

    def index
      @songs = if query_present? params
                 Song.search_song(params[:song_name],
                                  params[:singer_name],
                                  params[:category_name],
                                  params[:author_name])
               else
                 Song.includes(:author, :categories, :singers)
                     .sort_by_create_at
               end.paginate page: params[:page], per_page: 5
      respond_to do |format|
        format.html
        format.js
        format.xls { send_data Song.to_csv(col_sep: "\t") }
      end
    end

    def new
      @song = Song.new
    end

    def create
      @song = Song.new song_params
      if @song.save
        flash[:success] = 'Create Song Successfully!'
        redirect_to admins_songs_path
      else
        load_data
        render :new
      end
    end

    def edit; end

    def update
      if @song.update_attributes song_params
        redirect_to admins_songs_path
        flash[:success] = 'Song Edit Successfully!'
      else
        load_data
        render :edit
      end
    end

    def destroy
      @song.destroy
      flash[:success] = 'Song Delete Successfully!'
      redirect_to admins_songs_path
    end

    private

    def query_present?(params)
      params[:song_name].present? || params[:singer_name].present? ||
        params[:category_name].present? || params[:author_name].present?
    end

    def find_song
      @song = Song.find_by id: params[:id]
      return if @song
      flash[:danger] = 'Song not exits!'
      redirect_to admins_songs_path
    end

    def song_params
      params.require(:song).permit(
        :name, :content, :picture, :file_song,
        :author_id, :category_ids, :singer_ids, :album_ids
      )
    end

    def load_data
      @supports = Supports::Relationship.new
    end
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :check_user_logged, only: %i[new create]
  before_action :find_song, except: %i[index new create search]
  before_action :load_data, only: %i[index new edit]

  def index
    @songs = Song.includes(:singers).top
    @categories = Category.includes(:albums, albums: :songs).limit(3)
    @albums = Album.limit(6)
  end

  def new
    @song = Song.new
  end

  def create
    @song = Song.new song_params
    if @song.save
      flash[:success] = 'Create Song Successfully!'
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @song.update_attribute(:count_view, @song.count_view + 1)
    @favorites = Favorite.all
  end

  def edit; end

  def update
    if @song.update_attributes song_params
      redirect_to root_path
      flash[:success] = 'Song Edit Successfully!'
    else
      render :edit
    end
  end

  def destroy
    @song.destroy
    flash[:success] = 'Song Delete Successfully!'
    redirect_to root_path
  end

  def search
    @songs = if params[:search].present?
               Song.includes(:categories).search_song_client(params[:search])
             else
               Song.includes(:categories)
             end.paginate page: params[:page], per_page: 5
  end

  private

  def find_song
    @song = Song.find_by id: params[:id]
    return if @song
    flash[:danger] = 'Song not exits!'
    redirect_to root_path
  end

  def song_params
    params.require(:song).permit(
      :name, :content, :picture, :file_song, :author_id, :category_ids,
      :singer_ids
    )
  end

  def load_data
    @supports = Supports::Relationship.new
  end
end

app/views/admins/songs/_form.html.erb
<%= form_for [:admins, @song] do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  <div class="row">
    <div class="col-md-6 col-md-offset-1">
      <div class="form-group row">
        <div class="col-md-4">
          <%= f.label :name, t("views.admins.songs.text_form.name"),
            class: "col-form-label" %>
        </div>
        <div class="col-md-6">
          <%= f.text_field :name, class: "form-control" %>
        </div>
      </div>
      <div class="form-group row">
        <div class="col-md-4">
          <%= f.label :picture, t("views.admins.songs.text_form.images"),
            class: "col-form-label" %>
        </div>
        <div class="col-md-6">
          <%= f.file_field :picture %>
        </div>
      </div>
      <div class="form-group row">
        <div class="col-md-4">
          <%= f.label :file_song, t("views.admins.songs.text_form.url_song"),
            class: "col-form-label" %>
        </div>
        <div class="col-md-6">
          <%= f.file_field :file_song %>
        </div>
      </div>
      <div class="form-group row">
        <div class="col-md-4">
          <%= f.label :author_id, t("views.admins.authors.text_form.name"),
            class: "col-form-label" %>
        </div>
        <div class="col-md-6">
          <%= f.select :author_id, @supports.authors %>
        </div>
      </div>
      <div class="form-group row">
        <div class="col-md-4">
          <%= f.label :categories, t("views.admins.categories.text_form.name"),
            class: "col-form-label" %>
        </div>
        <div class="col-md-6">
          <%= f.select :category_ids, @supports.categories %>
        </div>
      </div>
      <div class='form-group row'>
        <div class='col-md-4'>
          <%= f.label :singers, t('views.admins.singers.text_form.name'),
            class: 'col-form-label' %>
        </div>
        <div class='col-md-6'>
          <%= f.select :singer_ids, @supports.singers %>
        </div>
      </div>
      <div class='form-group row'>
        <div class='col-md-4'>
          <%= f.label :albums, t('views.admins.albums.text_form.name'),
            class: 'col-form-label' %>
        </div>
        <div class='col-md-6'>
          <%= f.select :album_ids, @supports.albums %>
        </div>
      </div>
      <div class="form-group row">
        <div class="col-md-4">
          <%= f.label :content, t("views.admins.songs.text_form.content"),
            class: "col-form-label" %>
        </div>
        <div class="col-md-8">
          <%= f.cktext_area :content %>
        </div>
      </div>
    </div>
  <div class="row">
    <div class="form-group">
      <div class="col-md-6 col-md-offset-5">
        <%= f.submit yield(:button_text), class: "btn btn-success" %>
      </div>
    </div>
  </div>
<% end %>

app/views/admins/songs/_list_song.html.erb
<thead>
  <tr>
    <th><%= t "views.admins.songs.text_form.images" %></th>
    <th><%= t "views.admins.songs.text_form.name" %></th>
    <th><%= t "views.admins.authors.text_form.name" %></th>
    <th><%= t "views.admins.categories.text_form.name" %></th>
    <th><%= t 'views.admins.singers.text_form.name' %></th>
    <th>Count view</th>
    <th>Count Like</th>
    <th class="action"><%= t "views.admins.form.action" %></th>
  </tr>
</thead>
<tbody>
  <% @songs.each do |song| %>
    <tr class="background-tr">
      <td>
        <%= link_to "#", "data-toggle" => "modal", "data-target" => "#song_modal_#{song.id}" do %>
          <%= image_tag song.picture, class: "size-img-thumbnail" %>
        <% end %>
      </td>
      <td><%= song.name %></td>
      <td><%= song.author.name if song.author_id.present? %></td>
      <td>
      <% song.categories.each do |category| %>
        <%= category.name %>
      <% end %>
      </td>
      <td>
        <% song.singers.each do |singer| %>
          <%= singer.name %>
        <% end %>
      </td>
      <td><%= song.count_view %></td>
      <td><%= song.likes.count %></td>
      <td>
        <%= link_to edit_admins_song_path song do %>
          <i class="glyphicon glyphicon-pencil"></i>
        <% end %>
        <%= link_to admins_song_path(song), method: :delete,
          data: {confirm: t("views.admins.form_confirm")} do %>
          <i class="glyphicon glyphicon-trash"></i>
        <% end %>
      </td>
    </tr>
    <%= render "layouts/modal", song: song %>
  <% end %>
</tbody>

app/views/admins/songs/edit.html.erb
<% provide :title, t("views.admins.songs.title.edit") %>
<% provide :button_text, t("views.admins.songs.title.save") %>
<div class="main-content">
  <div class="container">
    <div class="info-manager">
      <div class="title-manager pull-left">
        <h2><%= t "views.admins.songs.title.edit" %></h2>
      </div>
      <div class="button-manager pull-right">
        <ul>
          <li>
            <%= link_to new_admins_song_path do %>
              <i class="glyphicon glyphicon-plus"></i>
              <%= t "button.create" %>
            <% end %>
          </li>
          <li>
            <%= link_to admins_songs_path(format: "xls") do %>
              <i class="glyphicon glyphicon-export"></i>
              <%= t "button.export" %>
            <% end %>
          </li>
        </ul>
      </div>
      <div class="clearfix"></div>
    </div>
    <div class="form-wrap">
      <%= render "form" %>
    </div>
  </div>
</div>

app/views/admins/songs/index.html.erb
<% provide :title, t("views.admins.songs.title.index") %>
<div class="main-content">
  <div class="container">
    <div class="info-manager">
      <div class="title-manager pull-left">
        <h2><%= t "views.admins.songs.title.index" %></h2>
      </div>
      <div class="button-manager pull-right">
        <ul>
          <li>
            <%= link_to new_admins_song_path do %>
              <i class="glyphicon glyphicon-plus"></i>
              <%= t "button.create" %>
            <% end %>
          </li>
          <li>
            <%= link_to admins_songs_path(format: "xls") do %>
              <i class="glyphicon glyphicon-export"></i>
              <%= t "button.export" %>
            <% end %>
          </li>
        </ul>
      </div>
      <div class="clearfix"></div>
    </div>
    <div class="row wrap-search">
      <div class="col-md-12">
        <%= form_tag admins_songs_path, method: :get, remote: true do %>
          <div class="form-group pull-right">
            <%= text_field_tag :song_name, params[:search],
              placeholder: "Song name" %>
            <%= select_tag :author_name, options_from_collection_for_select(
              Author.all, :name, :name, params[:seach]),
                include_blank: "Choose Author Name" %>
            <%= select_tag :category_name, options_from_collection_for_select(
              Category.all, :name, :name, params[:seach]),
                include_blank: "Choose Category Name" %>
            <%= select_tag :singer_name, options_from_collection_for_select(
              Singer.all, :name, :name, params[:seach]),
                include_blank: "Choose Singer Name" %>
            <%= button_tag "Seach", class: "custom-btn" do %>
              <span class="glyphicon glyphicon-search"></span>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
    <div class="table-responsive">
      <table class="table table-bordered table-hover">
       <%= render "list_song" %>
       <div class="paginate">
         <%= will_paginate %>
       </div>
      </table>
    </div>
  </div>
</div>

app/views/admins/songs/index.js.erb
$('.table').html('<%= j render "list_song" %>');
$('.paginate').html('<%= j will_paginate @songs %>')

app/views/admins/songs/new.html.erb
<% provide :title, t("views.admins.songs.title.new") %>
<% provide :button_text, t("views.admins.songs.title.new") %>
<div class="main-content">
  <div class="container">
    <div class="info-manager">
      <div class="title-manager pull-left">
        <h2><%= t "views.admins.songs.title.new" %></h2>
      </div>
      <div class="button-manager pull-right">
        <ul>
          <li>
            <%= link_to admins_songs_path(format: "xls") do %>
              <i class="glyphicon glyphicon-export"></i>
              <%= t "button.export" %>
            <% end %>
          </li>
        </ul>
      </div>
      <div class="clearfix"></div>
    </div>
    <div class="form-wrap">
      <%= render "form" %>
    </div>
  </div>
</div>