config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  scope "(:locale)", locale: /en|vi/ do

    root 'songs#index'

    devise_for :users, controllers: {registrations: "users/registrations",
      sessions: "users/sessions", passwords: "users/passwords", confirmations: "users/confirmations"}

    resources :favorites, only: %i[create show destroy]
    resources :favorite_songs, only: %i[create destroy]
    resources :songs do
      resources :comments
      collection do
        get 'search'
      end
    end
    resources :authors
    resources :categories
    resources :singers
    resources :albums do
      collection do
        get 'album_song'
      end
    end
    resources :users, only: :index
    resources :likes, only: %i[create destroy]

    namespace :admins do
      resources :users
      resources :songs
      resources :authors
      resources :categories
      resources :singers
      resources :albums
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  before_save :downcase_email

  scope :sort_by_create_at, -> { order created_at: :desc }
  scope :search_by_name, ->(search) { where 'name LIKE ?', "%#{search}%" }
  scope :search_by_permision, ->(search_permision) {
    where is_admin: search_permision
  }

  mount_uploader :image, PictureUploader

  has_many :likes
  has_many :comments

  has_many :songs, through: :user_songs
  has_many :user_songs, dependent: :destroy

  has_many :favorite

  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
    format: { with: VALID_EMAIL_REGEX },
      uniqueness: { case_sensitive: false }
  VALID_PASSWORD_REGEX = /^(?=.*[A-Za-z])(?=.*\d)[A-Za-z\d]{6,}$/
  validates :password, presence: true,
    length: { minimum: 6 }, allow_nil: true,
    format: { with: VALID_PASSWORD_REGEX, multiline: true,
    message: 'must be at least 6 characters and
      include one number and one letter.' }
  validates :phonenumber, length: { maximum: 10 }

  class << self
    def to_csv(options = {})
      CSV.generate options do |csv|
        csv << column_names
        all.each do |user|
          csv << user.attributes.values_at(*column_names)
        end
      end
    end

    def index_users(params)
      if params[:search].present? &&
         params[:search_by_permision].present?
        User.search_by_name(params[:search])
            .search_by_permision(params[:search_by_permision])
      elsif params[:search].present?
        User.search_by_name(params[:search])
      elsif params[:search_by_permision].present?
        User.search_by_permision(params[:search_by_permision])
      else
        User.sort_by_create_at
      end.paginate page: params[:page], per_page: 5
    end
  end

  private

  def downcase_email
    email.downcase!
  end
end

app/controllers/admins/users_controller.rb
module Admins
  class UsersController < ApplicationController
    layout 'application_admin'

    before_action :check_user_logged, :verify_admin
    before_action :find_user, except: %i[index new create]

    def index
      @users = User.index_users params
      respond_to do |format|
        format.html
        format.js
        format.xls { send_data User.to_csv(col_sep: "\t") }
      end
    end

    def new
      @user = User.new
    end

    def create
      @user = User.new user_params
      if @user.save
        flash[:success] = 'Create User Successfully!'
        redirect_to admins_users_path
      else
        render :new
      end
    end

    def show; end

    def edit; end

    def update
      if @user.update_attributes user_params
        redirect_to admins_users_path
        flash[:success] = 'User Edit Successfully!'
      else
        render :edit
      end
    end

    def destroy
      @user.destroy
      flash[:success] = 'User Delete Successfully!'
      redirect_to admins_users_path
    end

    private

    def find_user
      @user = User.find_by id: params[:id]
      return if @user
      flash[:danger] = 'User not exits!'
      redirect_to admins_users_path
    end

    def user_params
      params.require(:user).permit(
        :name, :email, :password,
        :password_confirmation,
        :address, :phonenumber,
        :is_admin,
        :image
      )
    end
  end
end

app/controllers/users/confirmations_controller.rb
module Users
  class ConfirmationsController < Devise::ConfirmationsController
    protected

    def after_confirmation_path_for(resource_name, _resource)
      root_path if signed_in?(resource_name)
    end
  end
end

app/controllers/users/passwords_controller.rb
module Users
  class PasswordsController < Devise::PasswordsController
    def after_resetting_password_path_for(_resource)
      root_path if Devise.sign_in_after_reset_password
    end

    def after_sending_reset_password_instructions_path_for(_resource_name)
      root_path if is_navigational_format?
    end
  end
end

app/controllers/users/registrations_controller.rb
module Users
  class RegistrationsController < Devise::RegistrationsController
    def create
      build_resource(sign_up_params)

      resource.save
      yield resource if block_given?
      if resource.persisted?
        flash[:success] = 'Please check your email for active account.!'
        redirect_to root_path
      else
        respond_to do |format|
          format.js
        end
      end
    end

    private

    def sign_up_params
      params.require(:user).permit(
        :image, :name, :email, :password,
        :password_confirmation, :address, :phonenumber
      )
    end

    def account_update_params
      params.require(:user).permit(
        :image, :name, :email, :phonenumber, :address, :password,
        :password_confirmation, :current_password
      )
    end
  end
end

app/controllers/users/sessions_controller.rb
module Users
  class SessionsController < Devise::SessionsController
    def new
      self.resource = resource_class.new(sign_in_params)
      clean_up_passwords(resource)
      yield resource if block_given?
      respond_to do |format|
        format.js
      end
    end

    def create
      if warden.authenticate?(auth_options)
        self.resource = warden.authenticate!(auth_options)
        flash[:success] = 'Signed in successfully.'
        sign_in(resource_name, resource)
        yield resource if block_given?
        respond_with resource, location: after_sign_in_path_for(resource)
      else
        respond_to do |format|
          format.js
        end
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @favorites = Favorite.all
  end
end

app/views/admins/users/_form.html.erb
<%= form_for [:admins, @user] do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <div class="form-group row">
        <div class="col-md-4">
          <%= f.label :name, t("views.admins.users.text_form.name"),
            class: "col-form-label" %>
        </div>
        <div class="col-md-6">
          <%= f.text_field :name, class: "form-control" %>
        </div>
      </div>
      <div class="form-group row">
        <div class="col-md-4">
          <%= f.label :image, t("views.admins.users.text_form.images"),
            class: "col-form-label" %>
        </div>
        <div class="col-md-6">
        <%= f.file_field :image %>
        </div>
      </div>
      <div class="form-group row">
        <div class="col-md-4">
          <%= f.label :email, t("views.admins.users.text_form.email"),
            class: "col-form-label" %>
        </div>
        <div class="col-md-6">
          <%= f.email_field :email, class: "form-control" %>
        </div>
      </div>
      <div class="form-group row">
        <div class="col-md-4">
          <%= f.label :password, class: "col-form-label" %>
        </div>
        <div class="col-md-6">
          <%= f.password_field :password, class: "form-control" %>
        </div>
      </div>
      <div class="form-group row">
        <div class="col-md-4">
          <%= f.label :password_confirmation,
            t("views.form.confirmation"), class: "col-form-label" %>
        </div>
        <div class="col-md-6">
          <%= f.password_field :password_confirmation,
            class: "form-control" %>
        </div>
      </div>
      <div class="form-group row">
        <div class="col-md-4">
          <%= f.label :phonenumber, t("views.admins.users.text_form.phone"),
            class: "col-form-label" %>
        </div>
        <div class="col-md-6">
          <%= f.number_field :phonenumber, class: "form-control" %>
        </div>
      </div>
      <div class="form-group row">
        <div class="col-md-4">
          <%= f.label :address, t("views.admins.users.text_form.address"),
            class: "col-form-label" %>
        </div>
        <div class="col-md-6">
          <%= f.text_field :address, class: "form-control" %>
        </div>
      </div>
      <div class="form-group row">
        <div class="col-md-4">
          <%= f.label :is_admin, t("views.admins.users.text_form.type"),
            class: "col-form-label" %>
        </div>
        <div class="col-md-6">
          <%= f.radio_button :is_admin, "true" %>
            <%= t "views.form.admin" %>
          <%= f.radio_button :is_admin, "false" %>
            <%= t "views.form.user" %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-md-6 col-md-offset-4">
          <%= f.submit yield(:button_text), class: "btn btn-success" %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/admins/users/_list_user.html.erb
<thead>
  <tr>
    <th><%= t "views.admins.users.text_form.images" %></th>
    <th><%= t "views.admins.users.text_form.name" %></th>
    <th><%= t "views.admins.users.text_form.email" %></th>
    <th><%= t "views.admins.users.text_form.phone" %></th>
    <th><%= t 'views.admins.users.text_form.address' %></th>
    <th><%= t 'views.admins.users.text_form.type' %></th>
    <th class="action"><%= t "views.admins.form.action" %></th>
  </tr>
</thead>
<tbody>
  <% @users.each do |user| %>
    <tr class="background-tr">
      <td><%= image_tag user.image, class: "size-img-thumbnail" %></td>
      <td><%= user.name %></td>
      <td><%= user.email %></td>
      <td><%= user.phonenumber %></td>
      <td><%= user.address %></td>
      <td><%= user.is_admin ? "Admin" : "User" %></td>
      <td>
        <%= link_to edit_admins_user_path user do %>
          <i class="glyphicon glyphicon-pencil"></i>
        <% end %>
        <%= link_to admins_user_path(user), method: :delete,
          data: {confirm: t("views.admins.form_confirm")} do %>
          <i class="glyphicon glyphicon-trash"></i>
        <% end %>
      </td>
    </tr>
  <% end %>
</tbody>

app/views/admins/users/edit.html.erb
<% provide :title, t("views.admins.users.title.edit") %>
<% provide :button_text, t("views.admins.users.title.save") %>
<div class="main-content">
  <div class="container">
    <div class="info-manager">
      <div class="title-manager pull-left">
        <h2><%= t "views.admins.users.title.edit" %></h2>
      </div>
      <div class="button-manager pull-right">
        <ul>
          <li>
            <%= link_to new_admins_user_path do %>
              <i class="glyphicon glyphicon-plus"></i>
              <%= t "button.create" %>
            <% end %>
          </li>
          <li>
            <%= link_to admins_users_path(format: "xls") do %>
              <i class="glyphicon glyphicon-export"></i>
              <%= t "button.export" %>
            <% end %>
          </li>
        </ul>
      </div>
      <div class="clearfix"></div>
    </div>
    <div class="form-wrap">
      <%= render "form" %>
    </div>
  </div>
</div>

app/views/admins/users/index.html.erb
<% provide :title, t("views.admins.users.title.index") %>
<div class="main-content">
  <div class="container">
    <div class="info-manager">
      <div class="title-manager pull-left">
        <h2><%= t "views.admins.users.title.index" %></h2>
      </div>
      <div class="button-manager pull-right">
        <ul>
          <li>
            <%= link_to new_admins_user_path do %>
              <i class="glyphicon glyphicon-plus"></i>
              <%= t "button.create" %>
            <% end %>
          </li>
          <li>
            <%= link_to admins_users_path(format: "xls") do %>
              <i class="glyphicon glyphicon-export"></i>
              <%= t "button.export" %>
            <% end %>
          </li>
        </ul>
      </div>
      <div class="clearfix"></div>
    </div>
    <div class="row wrap-search-user">
      <div class="col-md-12">
        <%= form_tag admins_users_path, method: :get, remote: true do %>
          <div class="form-group pull-left">
            <%= text_field_tag :search, params[:search],
              placeholder: "Input User Name" %>
            <%= button_tag "Search", class: "custom-btn" do %>
              <span class="glyphicon glyphicon-search"></span>
            <% end %>
          </div>
          <div class="form-group pull-right">
            <div>
              <%= check_box_tag :search_by_permision, "t" %>&nbsp;
              <%= t "views.form.admin" %>&nbsp;
              <%= check_box_tag :search_by_permision, "f" %>&nbsp;
              <%= t "views.form.user" %>&nbsp;
            </div>
          </div>
        <% end %>
      </div>
    </div>
    <div class="table-responsive">
      <div class="paginate">
        <%= will_paginate %>
      </div>
      <table class="table table-bordered table-hover">
        <%= render "list_user" %>
      </table>
    </div>
  </div>
</div>

app/views/admins/users/index.js.erb
$('.table').html('<%= j render "list_user" %>');
$('.paginate').html('<%= j will_paginate @users %>')

app/views/admins/users/new.html.erb
<% provide :title, t('views.admins.users.title.new') %>
<% provide :button_text, t('views.admins.users.title.new') %>
<div class="main-content">
  <div class="container">
    <div class="info-manager">
      <div class="title-manager pull-left">
        <h2><%= t 'views.admins.users.title.new' %></h2>
      </div>
      <div class="button-manager pull-right">
        <ul>
          <li>
            <%= link_to admins_users_path(format: "xls") do %>
              <i class="glyphicon glyphicon-export"></i>
                <%= t 'button.export' %>
            <% end %>
          </li>
        </ul>
      </div>
      <div class="clearfix"></div>
    </div>
    <div class="form-wrap">
      <%= render "form" %>
    </div>
  </div>
</div>