config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  scope "(:locale)", locale: /en|vi/ do

    root 'songs#index'

    devise_for :users, controllers: {registrations: "users/registrations",
      sessions: "users/sessions", passwords: "users/passwords", confirmations: "users/confirmations"}

    resources :favorites, only: %i[create show destroy]
    resources :favorite_songs, only: %i[create destroy]
    resources :songs do
      resources :comments
      collection do
        get 'search'
      end
    end
    resources :authors
    resources :categories
    resources :singers
    resources :albums do
      collection do
        get 'album_song'
      end
    end
    resources :users, only: :index
    resources :likes, only: %i[create destroy]

    namespace :admins do
      resources :users
      resources :songs
      resources :authors
      resources :categories
      resources :singers
      resources :albums
    end
  end
end

app/models/album.rb
class Album < ApplicationRecord
  scope :sort_by_create_at, -> { order created_at: :desc }
  scope :search_by_name, ->(search) { where 'name LIKE ?', "%#{search}%" }
  scope :limit_display, -> { (order created_at: :desc).limit(5) }

  validates :name, presence: true
  validates_presence_of :picture

  mount_uploader :picture, PictureUploader

  belongs_to :singer

  has_many :songs, through: :album_songs
  has_many :album_songs, dependent: :destroy

  has_many :categories, through: :album_categories
  has_many :album_categories, dependent: :destroy

  class << self
    def to_csv(options = {})
      CSV.generate options do |csv|
        csv << column_names
        all.each do |album|
          csv << album.attributes.values_at(*column_names)
        end
      end
    end

    def index_albums(params)
      if params[:search].present?
        Album.search_by_name(params[:search])
      else
        Album.includes(:singer, :categories).sort_by_create_at
      end.paginate page: params[:page], per_page: 5
    end
  end
end

app/controllers/admins/albums_controller.rb
module Admins
  class AlbumsController < ApplicationController
    layout 'application_admin'

    before_action :check_user_logged, :verify_admin
    before_action :find_album, except: %i[index new create]
    before_action :load_data, only: %i[index new edit]

    def index
      @albums = Album.index_albums params
      @album = Album.new
      respond_to do |format|
        format.html
        format.js
        format.xls { send_data Album.to_csv(col_sep: "\t") }
      end
    end

    def create
      @album = Album.new album_params
      if @album.save
        flash[:success] = 'Create Album Successfully!'
        redirect_to admins_albums_path
      else
        load_data
        render :new
      end
    end

    def edit; end

    def update
      if @album.update_attributes album_params
        redirect_to admins_albums_path
        flash[:success] = 'Album Edit Successfully!'
      else
        load_data
        render :edit
      end
    end

    def destroy
      if @album.destroy
        flash[:success] = 'Album Delete Successfully!'
      else
        flash[:danger] = 'Cant delete album'
      end
      redirect_to admins_albums_path
    end

    private

    def find_album
      @album = Album.includes(:songs, songs: :author)
                    .includes(:songs, songs: :categories)
                    .includes(:songs, songs: :singers)
                    .find_by id: params[:id]
      return if @album
      flash[:danger] = 'Album not exist'
      redirect_to admins_albums_path
    end

    def album_params
      params.require(:album).permit :name, :picture, :singer_id, :category_ids
    end

    def load_data
      @supports = Supports::Relationship.new
    end
  end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :find_album, only: %i[show edit update destroy]

  def show
    @album.update_attribute(:count_view, @album.count_view + 1)
  end

  def album_song
    @song = Song.find(params[:id])
    respond_to do |format|
      format.js
    end
  end

  private

  def find_album
    @album = Album.includes(:songs, songs: :singers).find_by id: params[:id]
    return if @album
    flash[:danger] = 'Album not exist'
    redirect_to root_path
  end
end

app/views/admins/albums/_form.html.erb
<%= form_for [:admins, @album], remote: true do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  <div class="row">
    <div class="col-md-8"">
      <div class="form-group row">
        <div class="col-md-5">
          <%= f.label :name, t("views.admins.albums.text_form.name"),
            class: "col-form-label" %>
        </div>
        <div class="col-md-7">
          <%= f.text_field :name, class: "form-control" %>
        </div>
      </div>
      <div class="form-group row">
        <div class="col-md-5">
          <%= f.label :picture, t("views.admins.albums.text_form.images"),
            class: "col-form-label" %>
        </div>
        <div class="col-md-7">
          <%= f.file_field :picture %>
        </div>
      </div>
      <div class="form-group row">
        <div class="col-md-5">
          <%= f.label :singer_id, t("views.admins.singers.text_form.name"),
            class: "col-form-label" %>
        </div>
        <div class="col-md-7">
          <%= f.select :singer_id, @supports.singers %>
        </div>
      </div>
      <div class="form-group row">
        <div class="col-md-5">
          <%= f.label :categories, t("views.admins.categories.text_form.name"),
            class: "col-form-label" %>
        </div>
        <div class="col-md-7">
          <%= f.select :category_ids, @supports.categories %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-md-7 col-md-offset-5">
          <%= f.submit button_to, class: "btn btn-success" %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/admins/albums/_list_album.html.erb
<thead>
  <tr>
    <th><%= t "views.admins.albums.text_form.images" %></th>
    <th><%= t "views.admins.albums.text_form.name" %></th>
    <th><%= t "views.admins.singers.text_form.name" %></th>
    <th><%= t "views.admins.categories.text_form.name" %></th>
    <th class="action"><%= t "views.admins.form.action" %></th>
  </tr>
</thead>
<tbody>
  <% @albums.each do |album| %>
    <tr class="background-tr">
      <td>
        <%= link_to admins_album_path(album) do %>
          <%= image_tag album.picture, class: "size-img-thumbnail" %>
        <% end %>
      </td>
      <td><%= album.name %></td>
      <td><%= album.singer.name if album.singer_id.present? %></td>
      <td>
        <% album.categories.each do |category| %>
          <%= category.name %>
        <% end %>
      </td>
      <td>
        <%= link_to edit_admins_album_path album do %>
          <i class="glyphicon glyphicon-pencil"></i>
        <% end %>
        <%= link_to admins_album_path(album), method: :delete,
          data: {confirm: t("views.admins.form_confirm")} do %>
          <i class="glyphicon glyphicon-trash"></i>
        <% end %>
      </td>
    </tr>
  <% end %>
</tbody>

app/views/admins/albums/_list_item.html.erb
<thead>
  <tr>
    <th><%= t "views.admins.songs.text_form.images" %></th>
    <th><%= t "views.admins.songs.text_form.name" %></th>
    <th><%= t "views.admins.authors.text_form.name" %></th>
    <th><%= t "views.admins.categories.text_form.name" %></th>
    <th><%= t 'views.admins.singers.text_form.name' %></th>
    <th class="action"><%= t "views.admins.form.action" %></th>
  </tr>
</thead>
<tbody>
  <% @album.songs.each do |song| %>
    <tr class="background-tr">
      <td>
        <%= link_to "#", "data-toggle" => "modal", "data-target" => "#song_modal_#{song.id}" do %>
          <%= image_tag song.picture, class: "size-img-thumbnail" %>
        <% end %>
      </td>
      <td><%= song.name %></td>
      <td><%= song.author.name if song.author_id.present? %></td>
      <td>
      <% song.categories.each do |category| %>
        <%= category.name %>
      <% end %>
      </td>
      <td>
        <% song.singers.each do |singer| %>
          <%= singer.name %>
        <% end %>
      </td>
      <td>
        <%= link_to edit_admins_song_path song do %>
          <i class="glyphicon glyphicon-pencil"></i>
        <% end %>
        <%= link_to admins_song_path(song), method: :delete,
          data: {confirm: t("views.admins.form_confirm")} do %>
          <i class="glyphicon glyphicon-trash"></i>
        <% end %>
      </td>
    </tr>
    <%= render "layouts/modal", song: song %>
  <% end %>
</tbody>

app/views/admins/albums/_new.html.erb
<div class="form-wrap">
<%= render 'form', button_to: t("views.admins.albums.title.new") %>
</div>

app/views/admins/albums/edit.html.erb
<% provide :title, t("views.admins.albums.title.edit") %>
<div class="main-content">
  <div class="container">
    <div class="info-manager">
      <div class="title-manager pull-left">
        <h2><%= t "views.admins.albums.title.edit" %></h2>
      </div>
      <div class="button-manager pull-right">
        <ul>
          <li>
            <%= link_to admins_albums_path(format: "xls") do %>
              <i class="glyphicon glyphicon-export"></i>
              <%= t "button.export" %>
            <% end %>
          </li>
        </ul>
      </div>
      <div class="clearfix"></div>
    </div>
    <div class="form-wrap">
      <%= render "form", button_to: t("views.admins.albums.title.save") %>
    </div>
  </div>
</div>

app/views/admins/albums/edit.js.erb
$('.form-wrap').html('<%= j render "form", button_to: t("views.admins.albums.title.save") %>');

app/views/admins/albums/index.html.erb
<% provide :title, t("views.admins.albums.title.index") %>
<div class="main-content">
  <div class="container">
    <div class="info-manager">
      <div class="title-manager pull-left">
        <h2><%= t "views.admins.albums.title.index" %></h2>
      </div>
      <div class="button-manager pull-right">
        <ul>
          <li>
            <%= link_to admins_albums_path(format: "xls") do %>
              <i class="glyphicon glyphicon-export"></i>
              <%= t "button.export" %>
            <% end %>
          </li>
        </ul>
      </div>
      <div class="clearfix"></div>
    </div>
    <div class="row wrap-search">
      <div class="col-md-6 col-md-offset-6">
        <%= form_tag admins_albums_path, method: :get, remote: true do %>
          <div class="form-group pull-right">
            <%= text_field_tag :search, params[:search],
              placeholder: "Input Name Album" %>
            <%= button_tag "Search", class: "custom-btn" do %>
              <span class="glyphicon glyphicon-search"></span>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-5">
        <%= render "new" %>
      </div>
      <div class="col-md-7">
        <div class="table-responsive">
          <table class="table table-bordered table-hover">
            <%= render "list_album" %>
          </table>
           <div class="paginate">
             <%= will_paginate %>
           </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admins/albums/index.js.erb
$('.table').html('<%= j render "list_album" %>');
$('.paginate').html('<%= j will_paginate @albums %>')

app/views/admins/albums/new.js.erb
$('.form-wrap').html('<%= j render "form", button_to: t("views.admins.albums.title.new") %>');

app/views/admins/albums/show.html.erb
<% provide :title, "Show song in album" %>
<div class="main-content">
  <div class="container">
    <div class="info-manager">
    </div>
    <div class="table-responsive">
      <table class="table table-bordered table-hover">
        <%= render "list_item" %>
      </table>
      <div class="pagination">
      </div>
    </div>
  </div>
</div>